### ISSUE TITLE
Strip unnecessary tags

### ISSUE THREAD

**Issue by max-baz** [GermainZ/aur-talk#2]
1. URLs are wrapped in `<` and `>` brackets, can we get rid of them?

`./aur_talk.py aurutils -n 20`, the last comment will say:

```
See <https://github.com/AladW/aurutils/releases/tag/1.5.0> for the full changelog.
```

Expected:

```
See https://github.com/AladW/aurutils/releases/tag/1.5.0 for the full changelog.
```

------------

2. Code blocks are wrapped in `[code]...[/code]`, I'd also prefer to get rid of them

`./aur_talk.py aurutils -n 11`, the last comment will say:

Current:

```
cat aurbuild.rej
[code] 
--- bin/aurbuild
    +++ bin/aurbuild
    @@ -5,7 +5,7 @@ readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
     set -e
    
     declare -a gpg_args=(--detach-sign --no-armor --verbose --batch)
-declare -a makechrootpkg_args=(-cnu) makepkg_args=(-Lcrs)
    +declare -a makechrootpkg_args=(-cnu) makepkg_args=(-crs)
     declare -i chroot=0 sign_pkg=0
    
     conf_chroot() {
    
[/code]
```

Expected:

```
cat aurbuild.rej

--- bin/aurbuild
    +++ bin/aurbuild
    @@ -5,7 +5,7 @@ readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
     set -e
    
     declare -a gpg_args=(--detach-sign --no-armor --verbose --batch)
-declare -a makechrootpkg_args=(-cnu) makepkg_args=(-Lcrs)
    +declare -a makechrootpkg_args=(-cnu) makepkg_args=(-crs)
     declare -i chroot=0 sign_pkg=0
    
     conf_chroot() {
    

```

----------

There are probably other tags, these are the ones I've just spotted. I basically want to see the plain text, not the markup.

**Comment by GermainZ** [comment]
[code] tags are no longer shown as per 0453db252329915460df6be770cbc8bfda1da837, since they're not necessary (code blocks are indented anyway).

For the URL delimiters, it's actually controlled by `html2text` and unfortunately can't be toggled without disabling URL handling altogether. I'd be happy to add an option for it if `html2text` adds support for that, though. (That being said, including them makes [a certain amount of sense](https://tools.ietf.org/html/rfc3986#appendix-C).)
